<?php

/**
 * Skeleton subclass for representing a row from the 'lausi_clientAddress' table.
 *
 * Base de Direcciones de Clientes
 *
 * This class was autogenerated by Propel on:
 *
 * Thu Mar 27 13:43:48 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lausi
 */
class ClientAddress extends BaseClientAddress {
	
	public function save(PropelPDO $con = null) {
		try {
			if ($this->validate()) { 
				parent::save($con);
				return true;
			} else {
				return false;
			}
		}
		catch (PropelException $exp) {
			if (ConfigModule::get("global","showPropelExceptions"))
				print_r($exp->getMessage());
			return false;
		}
	}
	
	function __toString() {
		/*TODO Agregar Nickname a dicrecciones de clientes
		$nickname = $this->getNickname();
		if (!empty($nickname))
			return $nickname;
		*/	
								
		if ($this->getNumber() != 0)
           	return $this->getStreet()." ".$this->getNumber();
		else
           	return $this->getStreet()." y ".$this->getIntersection();
	}
	
	/**
	 * Deprecated, usar __toString()
	 */
	function getName() {
		return $this->__toString();
	}

} // ClientAddress
