<?php

require_once 'om/BaseClient.php';


/**
 * Skeleton subclass for representing a row from the 'lausi_client' table.
 *
 * Base de Clientes
 *
 * This class was autogenerated by Propel on:
 *
 * Thu Mar 27 13:43:48 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lausi
 */
class Client extends BaseClient {

} // Client
