<?php

require_once 'om/BaseWorkforceCircuit.php';


/**
 * Skeleton subclass for representing a row from the 'lausi_workforceCircuit' table.
 *
 * 
 *
 * This class was autogenerated by Propel on:
 *
 * 03/27/08 13:57:36
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lausi
 */
class WorkforceCircuit extends BaseWorkforceCircuit {

} // WorkforceCircuit
