DELETE FROM `security_module` WHERE `module` = 'users';
INSERT INTO `security_module` ( `module` , `access` , `accessAffiliateUser` ) VALUES ('users', '0', '1');
DELETE FROM `security_action` WHERE `module` = 'users';
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersDoActivate','users','','1','5','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersDoAddToGroup','users','','1','1','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersDoDelete','users','','1','4','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersDoEdit','users','','1','0','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersDoLogin','users','','1','0','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersDoLogout','users','','1','0','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersDoPasswordRecovery','users','','1','0','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersDoRemoveFromGroup','users','','1','0','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersGroupsDoAddCategoryToGroup','users','','1','0','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersGroupsDoDelete','users','','1','0','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersGroupsDoEdit','users','','1','0','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersGroupsDoRemoveCatFromGroup','users','','1','0','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersGroupsList','users','','1073741823','1073741823','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersLevelsDoDelete','users','','1073741823','1073741823','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersLevelsDoEdit','users','','1073741823','1073741823','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersLevelsList','users','','1073741823','1073741823','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersList','users','','1073741823','1073741823','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersLogin','users','','1073741823','1073741823','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersLoginMaintenance','users','','1073741823','1073741823','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersPasswordRecovery','users','','1073741823','1073741823','1','');
INSERT INTO `security_action` (`action`,`module`,`section`,`access`,`accessAffiliateUser`, `active` , `pair` ) VALUES ('UsersWelcome','users','','1073741823','1073741823','1','');
