<?php

/**
 * Skeleton subclass for representing a row from the 'lausi_circuit' table.
 *
 * Base de Circuitos
 *
 * This class was autogenerated by Propel on:
 *
 * Thu Mar 27 13:43:48 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lausi
 */
class Circuit extends BaseCircuit {

	public function save(PropelPDO $con = null) {
		try {
			if ($this->validate()) { 
				parent::save($con);
				return true;
			} else {
				return false;
			}
		}
		catch (PropelException $exp) {
			if (ConfigModule::get("global","showPropelExceptions"))
				print_r($exp->getMessage());
			return false;
		}
	}

	public function getSheetsDistributed($themeId) {
		//duplicador
		$duplicator = 1;
		$theme = ThemePeer::get($themeId);
		$type = $theme->getType();
		//regla de negocio, las motivos dobles tienen dos afiches, los sextuples 1.
		if ($type == ThemePeer::TYPE_DOBLE)
			$duplicator = 2;
			
		$count = AdvertisementQuery::create()
			->filterByCircuit($this)
			->filterByTheme($theme)
			->count();
		
		return $count * $duplicator;
	}
	
	public function getAvailableTodayCount($theme) {
		$criteria = new BillboardQuery;
		$criteria->filterByType($theme->getType());
		$criteria->filterByCircuit($this);
		
		return BillboardPeer::getAllAvailableCount($criteria,date("Y-m-d"),1);
	}
	
	public function getBillboardsCount($type = null) {
		if (empty($type)) {
			$type = BillboardPeer::TYPE_SEXTUPLE;
		}
		
		$count = CircuitQuery::create()->countBillboards($this->getId(), $type);
		
		return $count;
	}

	/**
	 * Indica la cantidad de carteleras ocupadas por un theme el dia de hoy en el circuito
	 */
	public function getBillboardsOccupiedByThemeTodayCount($theme) {
		$criteria = BillboardQuery::create()
			->join('Advertisement')
			->filterByCircuit($this)
			->filterByTheme($theme)
			->useQuery('Advertisement')
				->filterByCurrent()
			->endUse()
			->distinct();
		
		$count = $criteria->count();
		
		return $count;
	}
} // Circuit
