<?php

require_once 'om/BaseWorkforce.php';



/**
 * Skeleton subclass for representing a row from the 'lausi_workforce' table.
 *
 * Base de Fuerza de Trabajo
 *
 * This class was autogenerated by Propel on:
 *
 * Thu Mar 27 13:43:48 2008
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lausi
 */
class Workforce extends BaseWorkforce {

	public function getCircuits() {
		
		$criteria = new Criteria();
		$criteria->add(WorkforceCircuitPeer::WORKFORCEID,$this->getId());
		$relationships = WorkforceCircuitPeer::doSelect($criteria);
		
		$elements = array();
		
		foreach($relationships as $relationship)
			array_push($elements,$relationship->getCircuit());
		
		return $elements;
	}
	
	/**
	 * Indica la cantidad de avisos sextuples asignados al contratista
	 * @param string fecha YYYY-MM-DD (opcional)
	 * @return array de instancias de Avisos
	 */
	public function getAssignedAdvertisementsCount($date=null) {
		
		require_once('AdvertisementPeer.php');
		
		$criteria = new Criteria();
		$criteria->add(AdvertisementPeer::WORKFORCEID,$this->getId());
		if ($date != null)
			$criteria->add(AdvertisementPeer::PUBLISHDATE,$date);
		
		return AdvertisementPeer::doCount($criteria);
		
	}


} // Workforce
