DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Common%' AND `language` = 'eng';
OPTIMIZE TABLE `security_actionLabel`;
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonConfigEdit', 'Edit config variables', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonActionLogsPurge', 'Purge action logs', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonConfigSet', 'Set config values', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonLogin', 'Users login', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonMenuItemsEdit', 'Edit menu items', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonMenuItemsShow', 'Show menu', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonActionLogsList', 'List actions logs', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonMenuItemsGetActionInfoX', 'Get menu item info', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonTemplatePublic', 'Show public external', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonSetLanguage', 'Set application language', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonGraph', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonJs', 'Generates JavaScript file', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonMenuItemsList', 'List menu items', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonMenuItemsDoEditOrderX', 'Edit menu items order', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonMaintenance', 'System under management redirect', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonMenuItemsActionsAutocompleteListX', 'Autocomplete actions for menu', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonIndex', 'Index redirect', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonMap', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonWelcome', 'Common User welcome', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('Js', 'Display js files', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonDoLogout', 'Common logout', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonMenuItemsDoDeleteX', 'Delete menu item', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonGenerateJs', 'Generates JavaScript file', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonConfigView', 'View config values', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('CommonCaptchaGeneration', 'Generates captcha', 'eng');
