<?php

/**
 * Skeleton subclass for representing a row from the 'usersByRegistration_user' table.
 *
 * Users by registration
 *
 * This class was autogenerated by Propel on:
 *
 * 08/15/07 01:55:57
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class UserByRegistration extends BaseUserByRegistration {
	
	function canChangeToUsername($username) {
		
		$usernameActual = $this->getUsername();
		if (strcmp(trim($usernameActual),trim($username)) != 0) {
			return !(UserByRegistrationPeer::usernameIsUsed($username));
		}
			
		return true;
		
	}
	
	function getUserInfo() {
		return $this->getUserByRegistrationInfo();
	}
	

} // UserByRegistration
