<?php

/**
 * Skeleton subclass for representing a row from the 'usersByRegistration_userInfo' table.
 *
 * Information about users by registration
 *
 * This class was autogenerated by Propel on:
 *
 * Tue Aug 21 17:21:52 2007
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class UserByRegistrationInfo extends BaseUserByRegistrationInfo {

} // UserByRegistrationInfo
