DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Modules%' AND `language` = 'eng';
OPTIMIZE TABLE `security_actionLabel`;
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesEdit', 'Edit module information', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesEntitiesEdit', 'Edit entities Information', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesEntitiesFieldsEdit', 'Edit Entities Fields', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesInstallFileCheck', 'Check installation files', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesInstallSetupActionsLabel', 'Manage actions labels', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesInstallSetupMessages', 'Setup action log messages', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesInstallSetupModuleInformation', 'Setup module informatio', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesInstallSetupPermissions', 'Setup module and action permissions', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesDoActivateX', 'Activate module', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesEntitiesAutocompleteListX', 'Autocomplete module entities ', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesEntitiesCreate', 'Create entities', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesEntitiesExportSchemas', 'Export xml schemas', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesEntitiesFieldsList', 'List Entities Fields ', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesEntitiesFieldsListX', 'Obtain the entitities available in system via Ajax', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesEntitiesList', 'List the entitites', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesEntitiesSchemaGet', 'Get modules xml schema', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesEntitiesSqlGet', 'Get entities sql information', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesInstallList', 'Mocule installation list', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesInstallModuleInformationSetup', 'Setup module information', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesInstallSetupSelectLanguages', 'Setup module installation languages', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('ModulesList', 'Modules list', 'eng');
